name: wallpaper_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_wallpaper_manager: ^0.0.4
  google_fonts: ^6.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo.png"
    min_sdk_android: 21

flutter:
  uses-material-design: true

assets:
  assets/